spring.application.name=Oauth-lab

spring.security.user.name=${SECURITY_USERNAME:am9}
spring.security.user.password=${SECURITY_PASSWORD:123}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %red(%-5level) %blue([%thread]) %yellow(%logger{15}) - %msg%n}
