spring.application.name=spring-security-lab

logging.level.org.springframework.security=TRACE
logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %yellow([%thread]) %red(%logger{15}) - %msg%n}
